# Generated by Django 6.0.3 on 2026-03-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_email_unique'),
        ('employee', '0005_remove_attendance_check_out_time_and_more'),
    ]

    operations = [
    ]
